### ISSUE TITLE
How to save the modified ELF?

### ISSUE THREAD

**Issue by jocutajar** [serge1/elfio-rs#1]
Hi,

I did not understand how can I save the modified ELF binary back into a file. Kindly advise.

Thank you

**Comment by serge1** [comment]
Please give a try to "add_section" example located in 'examples' directory.
Alternative method of ELF file modification is demonstrated in "anonymizer" example.

**Comment by serge1** [comment]
Oh, I am sorry. My reply belongs to the original C++ ELFIO project and not to its Rust little brother.
To the moment, the Rust version of the library implements ELF file reader only. The library does not permit creation or modification of ELF files yet. Therefore, there is no 'save' function available.

**Comment by jocutajar** [comment]
I have found the `object` crate... It's freaking complex... hands off :D
